version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nexus}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

  api:
    build: ./apps/api
    env_file:
      - ./.env
      - ./apps/api/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    command: /bin/bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build: ./apps/api
    env_file:
      - ./.env
      - ./apps/api/.env
    depends_on:
      - api
      - redis
    volumes:
      - ./apps/api:/app
    command: celery -A src.services.celery_app worker --loglevel=INFO

  web:
    build: ./apps/web
    env_file:
      - ./apps/web/.env
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules

volumes:
  dbdata:
